<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HalkaWorldMapEditor.Core\HalkaWorldMapEditor.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="SkiaSharp.Views.WPF" Version="3.119.1" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>HALKA WORLD MAP EDITOR</AssemblyName>
    <ApplicationIcon>Assets\map-editor.ico</ApplicationIcon>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\map-editor.ico" />
  </ItemGroup>

</Project>
